### ISSUE TITLE
Invalid namespace error on remote session

### ISSUE THREAD

**Issue by murrahjm** [PowerShell/CimPSDrive#7]
When trying to navigate a remote namespace that doesn't also exist on the local host, error "Invalid namespace" is returned.  Looking at line 106, it looks like the -cimsession parameter is missing, causing the request to run on the localhost rather than the remote machine.

**Comment by HemantMahawar** [comment]
@murrahjm Thanks for the issue and finding the root cause. Do you plan to submit a PR for it as well ;) ??

**Comment by murrahjm** [comment]
yep, doing that now.  pesky day job keeps getting in the way.
